export const provinces_commitee = [
  { name: "UBND tỉnh An Giang", id: "H01" },
  { name: "UBND tỉnh Bắc Giang", id: "H02" },
  { name: "UBND tỉnh Bắc Kạn", id: "H03" },
  { name: "UBND tỉnh Bạc Liêu", id: "H04" },
  { name: "UBND tỉnh Bắc Ninh", id: "H05" },
  { name: "UBND tỉnh Bà Rịa - Vũng Tàu", id: "H06" },
  { name: "UBND tỉnh Bến Tre", id: "H07" },
  { name: "UBND tỉnh Bình Định", id: "H08" },
  { name: "UBND tỉnh Bình Dương", id: "H09" },
  { name: "UBND tỉnh Bình Phước", id: "H10" },
  { name: "UBND tỉnh Bình Thuận", id: "H11" },
  { name: "UBND tỉnh Cà Mau", id: "H12" },
  { name: "UBND thành phố Cần Thơ", id: "H13" },
  { name: "UBND tỉnh Cao Bằng", id: "H14" },
  { name: "UBND tỉnh Đắk Lắk", id: "H15" },
  { name: "UBND tỉnh Đắk Nông", id: "H16" },
  { name: "UBND thành phố Đà Nẵng", id: "H17" },
  { name: "UBND tỉnh Điện Biên", id: "H18" },
  { name: "UBND tỉnh Đồng Nai", id: "H19" },
  { name: "UBND tỉnh Đồng Tháp", id: "H20" },
  { name: "UBND tỉnh Gia Lai", id: "H21" },
  { name: "UBND tỉnh Hà Giang", id: "H22" },
  { name: "UBND tỉnh Hải Dương", id: "H23" },
  { name: "UBND thành phố Hải Phòng", id: "H24" },
  { name: "UBND tỉnh Hà Nam", id: "H25" },
  { name: "UBND thành phố Hà Nội", id: "H26" },
  { name: "UBND tỉnh Hà Tĩnh", id: "H27" },
  { name: "UBND tỉnh Hòa Bình", id: "H28" },
  { name: "UBND Thành phố Hồ Chí Minh", id: "H29" },
  { name: "UBND tỉnh Hậu Giang", id: "H30" },
  { name: "UBND tỉnh Hưng Yên", id: "H31" },
  { name: "UBND tỉnh Khánh Hòa", id: "H32" },
  { name: "UBND tỉnh Kiên Giang", id: "H33" },
  { name: "UBND tỉnh Kon Tum", id: "H34" },
  { name: "UBND tỉnh Lai Châu", id: "H35" },
  { name: "UBND tỉnh Lâm Đồng", id: "H36" },
  { name: "UBND tỉnh Lạng Sơn", id: "H37" },
  { name: "UBND tỉnh Lào Cai", id: "H38" },
  { name: "UBND tỉnh Long An", id: "H39" },
  { name: "UBND tỉnh Nam Định", id: "H40" },
  { name: "UBND tỉnh Nghệ An", id: "H41" },
  { name: "UBND tỉnh Ninh Bình", id: "H42" },
  { name: "UBND tỉnh Ninh Thuận", id: "H43" },
  { name: "UBND tỉnh Phú Thọ", id: "H44" },
  { name: "UBND tỉnh Phú Yên", id: "H45" },
  { name: "UBND tỉnh Quảng Bình", id: "H46" },
  { name: "UBND tỉnh Quảng Nam", id: "H47" },
  { name: "UBND tỉnh Quảng Ngãi", id: "H48" },
  { name: "UBND tỉnh Quảng Ninh", id: "H49" },
  { name: "UBND tỉnh Quảng Trị", id: "H50" },
  { name: "UBND tỉnh Sóc Trăng", id: "H51" },
  { name: "UBND tỉnh Sơn La", id: "H52" },
  { name: "UBND tỉnh Tây Ninh", id: "H53" },
  { name: "UBND tỉnh Thái Bình", id: "H54" },
  { name: "UBND tỉnh Thái Nguyên", id: "H55" },
  { name: "UBND tỉnh Thanh Hóa", id: "H56" },
  { name: "UBND tỉnh Thừa Thiên Huế", id: "H57" },
  { name: "UBND tỉnh Tiền Giang", id: "H58" },
  { name: "UBND tỉnh Trà Vinh", id: "H59" },
  { name: "UBND tỉnh Tuyên Quang", id: "H60" },
  { name: "UBND tỉnh Vĩnh Long", id: "H61" },
  { name: "UBND tỉnh Vĩnh Phúc", id: "H62" },
  { name: "UBND tỉnh Yên Bái", id: "H63" },
];

export const provinces_council = [
  { name: "HĐND tỉnh An Giang", id: "K01" },
  { name: "HĐND tỉnh Bắc Giang", id: "K02" },
  { name: "HĐND tỉnh Bắc Kạn", id: "K03" },
  { name: "HĐND tỉnh Bạc Liêu", id: "K04" },
  { name: "HĐND tỉnh Bắc Ninh", id: "K05" },
  { name: "HĐND tỉnh Bà Rịa - Vũng Tàu", id: "K06" },
  { name: "HĐND tỉnh Bến Tre", id: "K07" },
  { name: "HĐND tỉnh Bình Định", id: "K08" },
  { name: "HĐND tỉnh Bình Dương", id: "K09" },
  { name: "HĐND tỉnh Bình Phước", id: "K10" },
  { name: "HĐND tỉnh Bình Thuận", id: "K11" },
  { name: "HĐND tỉnh Cà Mau", id: "K12" },
  { name: "HĐND thành phố Cần Thơ", id: "K13" },
  { name: "HĐND tỉnh Cao Bằng", id: "K14" },
  { name: "HĐND tỉnh Đắk Lắk", id: "K15" },
  { name: "HĐND tỉnh Đắk Nông", id: "K16" },
  { name: "HĐND thành phố Đà Nẵng", id: "K17" },
  { name: "HĐND tỉnh Điện Biên", id: "K18" },
  { name: "HĐND tỉnh Đồng Nai", id: "K19" },
  { name: "HĐND tỉnh Đồng Tháp", id: "K20" },
  { name: "HĐND tỉnh Gia Lai", id: "K21" },
  { name: "HĐND tỉnh Hà Giang", id: "K22" },
  { name: "HĐND tỉnh Hải Dương", id: "K23" },
  { name: "HĐND thành phố Hải Phòng", id: "K24" },
  { name: "HĐND tỉnh Hà Nam", id: "K25" },
  { name: "HĐND thành phố Hà Nội", id: "K26" },
  { name: "HĐND tỉnh Hà Tĩnh", id: "K27" },
  { name: "HĐND tỉnh Hòa Bình", id: "K28" },
  { name: "HĐND Thành phố Hồ Chí Minh", id: "K29" },
  { name: "HĐND tỉnh Hậu Giang", id: "K30" },
  { name: "HĐND tỉnh Hưng Yên", id: "K31" },
  { name: "HĐND tỉnh Khánh Hòa", id: "K32" },
  { name: "HĐND tỉnh Kiên Giang", id: "K33" },
  { name: "HĐND tỉnh Kon Tum", id: "K34" },
  { name: "HĐND tỉnh Lai Châu", id: "K35" },
  { name: "HĐND tỉnh Lâm Đồng", id: "K36" },
  { name: "HĐND tỉnh Lạng Sơn", id: "K37" },
  { name: "HĐND tỉnh Lào Cai", id: "K38" },
  { name: "HĐND tỉnh Long An", id: "K39" },
  { name: "HĐND tỉnh Nam Định", id: "K40" },
  { name: "HĐND tỉnh Nghệ An", id: "K41" },
  { name: "HĐND tỉnh Ninh Bình", id: "K42" },
  { name: "HĐND tỉnh Ninh Thuận", id: "K43" },
  { name: "HĐND tỉnh Phú Thọ", id: "K44" },
  { name: "HĐND tỉnh Phú Yên", id: "K45" },
  { name: "HĐND tỉnh Quảng Bình", id: "K46" },
  { name: "HĐND tỉnh Quảng Nam", id: "K47" },
  { name: "HĐND tỉnh Quảng Ngãi", id: "K48" },
  { name: "HĐND tỉnh Quảng Ninh", id: "K49" },
  { name: "HĐND tỉnh Quảng Trị", id: "K50" },
  { name: "HĐND tỉnh Sóc Trăng", id: "K51" },
  { name: "HĐND tỉnh Sơn La", id: "K52" },
  { name: "HĐND tỉnh Tây Ninh", id: "K53" },
  { name: "HĐND tỉnh Thái Bình", id: "K54" },
  { name: "HĐND tỉnh Thái Nguyên", id: "K55" },
  { name: "HĐND tỉnh Thanh Hóa", id: "K56" },
  { name: "HĐND tỉnh Thừa Thiên Huế", id: "K57" },
  { name: "HĐND tỉnh Tiền Giang", id: "K58" },
  { name: "HĐND tỉnh Trà Vinh", id: "K59" },
  { name: "HĐND tỉnh Tuyên Quang", id: "K60" },
  { name: "HĐND tỉnh Vĩnh Long", id: "K61" },
  { name: "HĐND tỉnh Vĩnh Phúc", id: "K62" },
  { name: "HĐND tỉnh Yên Bái", id: "K63" },
];

export const ministries = [
  { name: "Bộ Công an", id: "G01" },
  { name: "Bộ Công Thương", id: "G02" },
  { name: "Bộ Giáo dục và Đào tạo", id: "G03" },
  { name: "Bộ Giao thông vận tải", id: "G04" },
  { name: "Bộ Kế hoạch và Đầu tư", id: "G05" },
  { name: "Bộ Khoa học và Công nghệ", id: "G06" },
  { name: "Bộ Lao động - Thương binh và Xã hội", id: "G07" },
  { name: "Bộ Ngoại giao", id: "G08" },
  { name: "Bộ Nội vụ", id: "G09" },
  { name: "Bộ Nông nghiệp và Phát triển nông thôn", id: "G10" },
  { name: "Bộ Quốc phòng", id: "G11" },
  { name: "Bộ Tài chính", id: "G12" },
  { name: "Bộ Tài nguyên và Môi trường", id: "G13" },
  { name: "Bộ Thông tin và Truyền thông", id: "G14" },
  { name: "Bộ Tư pháp", id: "G15" },
  { name: "Bộ Văn hóa, Thể thao và Du lịch", id: "G16" },
  { name: "Bộ Xây dựng", id: "G17" },
  { name: "Bộ Y tế", id: "G18" },
  { name: "Ngân hàng Nhà nước Việt Nam", id: "G19" },
  { name: "Thanh tra Chính phủ", id: "G20" },
  { name: "Ủy ban Dân tộc", id: "G21" },
  { name: "Văn phòng Chính phủ", id: "G22" },
  { name: "Ban Quản lý lăng Chủ tịch Hồ Chí Minh", id: "G23" },
  { name: "Bảo hiểm Xã hội Việt Nam", id: "G24" },
  { name: "Đại học Quốc gia Hà Nội", id: "G25" },
  { name: "Đại học Quốc gia Thành phố Hồ Chí Minh", id: "G26" },
  { name: "Đài Tiếng nói Việt Nam", id: "G27" },
  { name: "Đài Truyền hình Việt Nam", id: "G28" },
  { name: "Viện Hàn lâm Khoa học và Công nghệ Việt Nam", id: "G31" },
  { name: "Viện Hàn lâm Khoa học xã hội Việt Nam", id: "G32" },
  { name: "Ủy ban Giám sát tài chính Quốc gia", id: "G34" },
  { name: "Ủy ban An toàn giao thông Quốc gia", id: "G35" },
  { name: "Ủy ban Quản lý vốn nhà nước tại doanh nghiệp", id: "G36" },
];

export const provinces = [
  { name: "An Giang", id: "01" },
  { name: "Bắc Giang", id: "02" },
  { name: "Bắc Kạn", id: "03" },
  { name: "Bạc Liêu", id: "04" },
  { name: "Bắc Ninh", id: "05" },
  { name: "Bà Rịa - Vũng Tàu", id: "06" },
  { name: "Bến Tre", id: "07" },
  { name: "Bình Định", id: "08" },
  { name: "Bình Dương", id: "09" },
  { name: "Bình Phước", id: "10" },
  { name: "Bình Thuận", id: "11" },
  { name: "Cà Mau", id: "12" },
  { name: "Cần Thơ", id: "13" },
  { name: "Cao Bằng", id: "14" },
  { name: "Đắk Lắk", id: "15" },
  { name: "Đắk Nông", id: "16" },
  { name: "Đà Nẵng", id: "17" },
  { name: "Điện Biên", id: "18" },
  { name: "Đồng Nai", id: "19" },
  { name: "Đồng Tháp", id: "20" },
  { name: "Gia Lai", id: "21" },
  { name: "Hà Giang", id: "22" },
  { name: "Hải Dương", id: "23" },
  { name: "Hải Phòng", id: "24" },
  { name: "Hà Nam", id: "25" },
  { name: "Hà Nội", id: "26" },
  { name: "Hà Tĩnh", id: "27" },
  { name: "Hòa Bình", id: "28" },
  { name: "Hồ Chí Minh", id: "29" },
  { name: "Hậu Giang", id: "30" },
  { name: "Hưng Yên", id: "31" },
  { name: "Khánh Hòa", id: "32" },
  { name: "Kiên Giang", id: "33" },
  { name: "Kon Tum", id: "34" },
  { name: "Lai Châu", id: "35" },
  { name: "Lâm Đồng", id: "36" },
  { name: "Lạng Sơn", id: "37" },
  { name: "Lào Cai", id: "38" },
  { name: "Long An", id: "39" },
  { name: "Nam Định", id: "40" },
  { name: "Nghệ An", id: "41" },
  { name: "Ninh Bình", id: "42" },
  { name: "Ninh Thuận", id: "43" },
  { name: "Phú Thọ", id: "44" },
  { name: "Phú Yên", id: "45" },
  { name: "Quảng Bình", id: "46" },
  { name: "Quảng Nam", id: "47" },
  { name: "Quảng Ngãi", id: "48" },
  { name: "Quảng Ninh", id: "49" },
  { name: "Quảng Trị", id: "50" },
  { name: "Sóc Trăng", id: "51" },
  { name: "Sơn La", id: "52" },
  { name: "Tây Ninh", id: "53" },
  { name: "Thái Bình", id: "54" },
  { name: "Thái Nguyên", id: "55" },
  { name: "Thanh Hóa", id: "56" },
  { name: "Thừa Thiên Huế", id: "57" },
  { name: "Tiền Giang", id: "58" },
  { name: "Trà Vinh", id: "59" },
  { name: "Tuyên Quang", id: "60" },
  { name: "Vĩnh Long", id: "61" },
  { name: "Vĩnh Phúc", id: "62" },
  { name: "Yên Bái", id: "63" },
];

export const docTypes = [
  { id: "1", name: "Hiến pháp" },
  { id: "2", name: "Bộ luật" },
  { id: "3", name: "Luật" },
  { id: "4", name: "Nghị quyết" },
  { id: "5", name: "Pháp lệnh" },
  { id: "6", name: "Quyết định" },
  { id: "7", name: "Nghị định" },
  { id: "8", name: "Thông tư" },
  { id: "9", name: "Nghị quyết liên tịch" },
];
